name: On Pull Request Cancelled

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  upgrade:

    name: Upgrade packages
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cancelling in progress runs"
